apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: prathameshkalekar/demo-app:dev
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "400m"
